### ISSUE TITLE
CLI token generation

### ISSUE THREAD

**Issue by ferreroltd** [salamaashoush/design-sync#42]
While doing the token sync there may be an issue where it would name the style names incorrectly, like its only taking the last 3 elements, making the naming of the 2 attached images as monospaceBaseRegular, thus breaking on the const exports
![image (1)](https://github.com/salamaashoush/design-sync/assets/73488793/2e0cef4c-d26c-4897-a9e8-7e4bc83c44b4)
![image](https://github.com/salamaashoush/design-sync/assets/73488793/0a9765be-677c-413e-889b-8bc0093dfab7)

**Comment by salamaashoush** [comment]
I released a new version with the ability to use a custom function to generate a style name, here is an example of how you could use it

![image](https://github.com/salamaashoush/design-sync/assets/13505298/3729cabe-6853-4b9c-be6f-f9f9ea486b58)

**Comment by salamaashoush** [comment]
for more flexibility `styleName` now has the full token as first parameter so you can use more info to decide the style name
